import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import type { DatabaseClient } from '../../shared/supabase/client'
import { postQueryKeys } from '../posts/posts.queries'
import { newsTopicQueryKeys } from '../newsTopics/newsTopics.queries'
import { createNewsUpdate, getNewsUpdateById, listAssignableSources, listPostNewsUpdates, listPreviousUpdateCandidates, listTopicNewsUpdates, reorderNewsUpdates, updateNewsUpdate } from './newsUpdates.repository'
import type { CreateNewsUpdateInput, SaveNewsUpdateInput } from './newsUpdates.types'
export const newsUpdateQueryKeys = { all: ['news-updates'] as const, post: (u: string, p: string) => ['news-updates', 'post', u, p] as const, topic: (u: string, t: string) => ['news-updates', 'topic', u, t] as const, detail: (u: string, id: string) => ['news-updates', 'detail', u, id] as const, previous: (u: string, t: string, before = '') => ['news-updates', 'previous', u, t, before] as const, sources: (u: string, p: string, id = '') => ['news-updates', 'sources', u, p, id] as const }
function requireClient(client: DatabaseClient | null) { if (!client) throw new Error('Supabase 연결이 설정되지 않았습니다.'); return client }
export function usePostNewsUpdatesQuery(c: DatabaseClient | null, u: string, p: string) { return useQuery({ queryKey: newsUpdateQueryKeys.post(u, p), queryFn: () => listPostNewsUpdates(requireClient(c), p), enabled: !!c && !!u && !!p, retry: false }) }
export function useTopicNewsUpdatesQuery(c: DatabaseClient | null, u: string, t: string) { return useQuery({ queryKey: newsUpdateQueryKeys.topic(u, t), queryFn: () => listTopicNewsUpdates(requireClient(c), t), enabled: !!c && !!u && !!t, retry: false }) }
export function useNewsUpdateQuery(c: DatabaseClient | null, u: string, id: string) { return useQuery({ queryKey: newsUpdateQueryKeys.detail(u, id), queryFn: () => getNewsUpdateById(requireClient(c), id), enabled: !!c && !!u && !!id, retry: false }) }
export function usePreviousUpdatesQuery(c: DatabaseClient | null, u: string, t: string, before?: string) { return useQuery({ queryKey: newsUpdateQueryKeys.previous(u, t, before), queryFn: () => listPreviousUpdateCandidates(requireClient(c), t, before), enabled: !!c && !!u && !!t, retry: false }) }
export function useAssignableSourcesQuery(c: DatabaseClient | null, u: string, p: string, id?: string) { return useQuery({ queryKey: newsUpdateQueryKeys.sources(u, p, id), queryFn: () => listAssignableSources(requireClient(c), p, id), enabled: !!c && !!u && !!p, retry: false }) }
function invalidate(qc: ReturnType<typeof useQueryClient>, u: string, p: string, t: string, id?: string) { void qc.invalidateQueries({ queryKey: newsUpdateQueryKeys.post(u, p) }); void qc.invalidateQueries({ queryKey: newsUpdateQueryKeys.topic(u, t) }); void qc.invalidateQueries({ queryKey: postQueryKeys.sources(u, p) }); void qc.invalidateQueries({ queryKey: newsTopicQueryKeys.detail(u, t) }); if (id) void qc.invalidateQueries({ queryKey: newsUpdateQueryKeys.detail(u, id) }) }
export function useCreateNewsUpdateMutation(c: DatabaseClient | null, u: string) { const qc = useQueryClient(); return useMutation({ mutationFn: (input: CreateNewsUpdateInput) => createNewsUpdate(requireClient(c), input), onSuccess: (item, input) => invalidate(qc, u, input.postId, input.topicId, item.id) }) }
export function useUpdateNewsUpdateMutation(c: DatabaseClient | null, u: string, item: { id: string; postId: string; topicId: string }) { const qc = useQueryClient(); return useMutation({ mutationFn: (input: SaveNewsUpdateInput) => updateNewsUpdate(requireClient(c), item.id, input), onSuccess: () => invalidate(qc, u, item.postId, item.topicId, item.id) }) }
export function useReorderNewsUpdatesMutation(c: DatabaseClient | null, u: string, p: string) { const qc = useQueryClient(); return useMutation({ mutationFn: (ids: string[]) => reorderNewsUpdates(requireClient(c), p, ids), onSuccess: () => void qc.invalidateQueries({ queryKey: newsUpdateQueryKeys.post(u, p) }) }) }
