import { zodResolver } from '@hookform/resolvers/zod'
import { useEffect } from 'react'
import { useForm, useWatch } from 'react-hook-form'
import type { NewsTopic } from '../newsTopics/newsTopics.types'
import { newsUpdateFormSchema, type NewsUpdateFormValues } from './newsUpdateFormSchema'
import { newsUpdateTypeLabels, newsUpdateTypes, type AssignableSource, type NewsUpdate } from './newsUpdates.types'

interface Props { post: { category_id: string; title: string; display_id: string | null }; topics: NewsTopic[]; previous: NewsUpdate[]; sources: AssignableSource[]; initial?: NewsUpdateFormValues; editing?: boolean; pending?: boolean; error?: string | null; onTopicChange?: (id: string) => void; onSubmit: (values: NewsUpdateFormValues) => Promise<void> }
const defaults: NewsUpdateFormValues = { topicId: '', updateType: 'new', headline: '', factSummary: '', importanceSummary: '', impactSummary: '', changeSummary: '', previousUpdateId: '', sourceIds: [] }
export function NewsUpdateForm({ post, topics, previous, sources, initial = defaults, editing = false, pending = false, error, onTopicChange, onSubmit }: Props) {
  const { register, handleSubmit, control, setValue, setError, formState: { errors } } = useForm<NewsUpdateFormValues>({ resolver: zodResolver(newsUpdateFormSchema), defaultValues: initial })
  const updateType = useWatch({ control, name: 'updateType' }); const topicId = useWatch({ control, name: 'topicId' }); const selectedTopic = topics.find((topic) => topic.id === topicId)
  useEffect(() => { onTopicChange?.(topicId) }, [onTopicChange, topicId])
  async function submit(values: NewsUpdateFormValues) { if (selectedTopic?.category_id !== post.category_id) { setError('topicId', { message: '뉴스 게시물과 뉴스 주제의 카테고리가 일치하지 않습니다.' }); return } if (values.updateType === 'closure_note' && selectedTopic?.status !== 'closed') { setError('updateType', { message: '종료 메모는 종료된 뉴스 주제에만 추가할 수 있습니다.' }); return } await onSubmit(values) }
  return <form className="post-form" onSubmit={handleSubmit(submit)} noValidate>
    <section className="post-form__section"><h2>기본 연결 정보</h2><p className="field-help">게시물: {post.display_id ?? post.title}</p><div className="post-form__field"><label htmlFor="news-update-topic">뉴스 주제</label><select id="news-update-topic" disabled={editing} {...register('topicId')}><option value="">선택</option>{topics.filter((topic) => topic.category_id === post.category_id).map((topic) => <option key={topic.id} value={topic.id}>{topic.canonical_title} ({topic.status})</option>)}</select>{errors.topicId ? <p className="field-error">{errors.topicId.message}</p> : null}</div><div className="post-form__field"><label htmlFor="news-update-type">업데이트 유형</label><select id="news-update-type" disabled={editing} {...register('updateType')} onChange={(event) => { const value = event.target.value as NewsUpdateFormValues['updateType']; setValue('updateType', value, { shouldValidate: true }); if (value === 'new') setValue('previousUpdateId', '') }}>{newsUpdateTypes.map((value) => <option key={value} value={value}>{newsUpdateTypeLabels[value]}</option>)}</select>{errors.updateType ? <p className="field-error">{errors.updateType.message}</p> : null}</div></section>
    <section className="post-form__section"><h2>핵심 내용</h2><div className="post-form__field"><label htmlFor="news-update-headline">뉴스 항목 제목</label><input id="news-update-headline" {...register('headline')} />{errors.headline ? <p className="field-error">{errors.headline.message}</p> : null}</div><div className="post-form__field"><label htmlFor="news-update-fact">확인된 사실 요약</label><textarea id="news-update-fact" rows={5} {...register('factSummary')} />{errors.factSummary ? <p className="field-error">{errors.factSummary.message}</p> : null}</div><div className="post-form__field"><label htmlFor="news-update-importance">중요성 (선택)</label><textarea id="news-update-importance" rows={3} {...register('importanceSummary')} /></div><div className="post-form__field"><label htmlFor="news-update-impact">영향 (선택)</label><textarea id="news-update-impact" rows={3} {...register('impactSummary')} /></div></section>
    <section className="post-form__section"><h2>이전 업데이트 연결</h2>{updateType !== 'new' ? <div className="post-form__field"><label htmlFor="news-update-previous">이전 업데이트</label><select id="news-update-previous" {...register('previousUpdateId')}><option value="">선택</option>{previous.map((item) => <option key={item.id} value={item.id}>{item.post.briefing_date ?? '날짜 없음'} · {newsUpdateTypeLabels[item.update_type as keyof typeof newsUpdateTypeLabels] ?? item.update_type} · {item.headline} · {item.post.display_id ?? item.post.title}</option>)}</select>{errors.previousUpdateId ? <p className="field-error">{errors.previousUpdateId.message}</p> : null}</div> : null}<div className="post-form__field"><label htmlFor="news-update-change">이전 대비 변화{updateType === 'new' ? ' (선택)' : ''}</label><textarea id="news-update-change" rows={4} {...register('changeSummary')} /><p className="field-help">표현 반복이 아니라 새 수치·공식 결정·후속 조치 등 실제 변화를 적어 주세요.</p>{errors.changeSummary ? <p className="field-error">{errors.changeSummary.message}</p> : null}</div></section>
    <section className="post-form__section"><h2>연결 출처</h2>{sources.length ? <fieldset className="checkbox-list"><legend>이 뉴스 항목의 근거 출처를 하나 이상 선택해 주세요.</legend>{sources.map((source) => <label key={source.id}><input type="checkbox" value={source.id} {...register('sourceIds')} /><span><strong>{source.source_name}</strong> — {source.source_title}</span></label>)}</fieldset> : <p className="field-help">연결할 수 있는 출처가 없습니다. 먼저 게시물 편집에서 출처를 등록해 주세요.</p>}{errors.sourceIds ? <p className="field-error">{errors.sourceIds.message}</p> : null}</section>
    <aside className="content-detail__section" aria-label="의미 있는 업데이트 기준"><h2>업데이트 편집 기준</h2><p>공식 발표, 새로운 수치, 정책 확정, 법적 결정, 기업 후속 조치, 중대한 변화, 오류 수정, 실제 영향을 기록합니다.</p><p className="field-help">제목만 다른 반복 보도, 표현만 바뀐 동일 내용, 새 사실 없는 재인용과 전망 반복은 새 업데이트로 기록하지 않습니다.</p></aside>
    {error ? <p className="form-alert" role="alert">{error}</p> : null}<div className="post-form__actions"><button className="primary-button" type="submit" disabled={pending}>{pending ? '저장 중' : '뉴스 항목 저장'}</button></div>
  </form>
}
