import type { DatabaseClient } from '../../shared/supabase/client'
import type { AssignableSource, CreateNewsUpdateInput, NewsUpdate, NewsUpdateRow, SaveNewsUpdateInput } from './newsUpdates.types'

const updateFields = 'id, post_id, topic_id, item_order, update_type, headline, fact_summary, importance_summary, impact_summary, change_summary, previous_update_id, created_at, updated_at'
const detailFields = `${updateFields}, post:posts!news_updates_post_owner_fkey(id, title, display_id, briefing_date), topic:news_topics!news_updates_topic_owner_fkey(id, canonical_title, category_id, status), sources(id, source_name, source_title, source_url, checked_point)`
interface RepositoryError { code?: string; message?: string; details?: string }
function throwUpdateError(error: RepositoryError): never { const detail = `${error.message ?? ''} ${error.details ?? ''}`; if (detail.includes('CATEGORY_MISMATCH')) throw new Error('뉴스 게시물과 뉴스 주제의 카테고리가 일치하지 않습니다.'); if (detail.includes('PREVIOUS_REQUIRED')) throw new Error('후속·정정 업데이트에는 이전 업데이트가 필요합니다.'); if (detail.includes('CHANGE_REQUIRED')) throw new Error('이전 업데이트와 비교한 변경 내용을 입력해 주세요.'); if (detail.includes('PREVIOUS_TOPIC') || detail.includes('PREVIOUS_SELF')) throw new Error('이전 업데이트는 같은 뉴스 주제에 속해야 합니다.'); if (detail.includes('CLOSED_TOPIC')) throw new Error('종료 메모는 종료된 뉴스 주제에만 추가할 수 있습니다.'); if (detail.includes('SOURCE_REQUIRED')) throw new Error('하나 이상의 출처를 연결해 주세요.'); if (detail.includes('SOURCE_INVALID')) throw new Error('선택한 출처를 이 뉴스 항목에 연결할 수 없습니다.'); if (detail.includes('REORDER')) throw new Error('뉴스 항목 순서를 저장할 수 없습니다.'); if (error.code === '42501' || detail.includes('NOT_FOUND')) throw new Error('뉴스 항목을 찾을 수 없거나 접근 권한이 없습니다.'); throw new Error('뉴스 항목 저장 중 오류가 발생했습니다.') }
function asUpdate(data: unknown) { return data as NewsUpdate }

export async function listPostNewsUpdates(client: DatabaseClient, postId: string): Promise<NewsUpdate[]> { const { data, error } = await client.from('news_updates').select(detailFields).eq('post_id', postId).order('item_order'); if (error) throw new Error('뉴스 항목을 불러오지 못했습니다.'); return data.map(asUpdate) }
export async function listTopicNewsUpdates(client: DatabaseClient, topicId: string): Promise<NewsUpdate[]> { const { data, error } = await client.from('news_updates').select(detailFields).eq('topic_id', topicId).order('created_at', { ascending: false }); if (error) throw new Error('업데이트 이력을 불러오지 못했습니다.'); return data.map(asUpdate).sort((a, b) => (b.post.briefing_date ?? '').localeCompare(a.post.briefing_date ?? '') || b.created_at.localeCompare(a.created_at)) }
export async function getNewsUpdateById(client: DatabaseClient, id: string): Promise<NewsUpdate | null> { const { data, error } = await client.from('news_updates').select(detailFields).eq('id', id).maybeSingle(); if (error) { if (error.code === '22P02' || error.code === 'PGRST116') return null; throw new Error('뉴스 항목을 불러오지 못했습니다.') } return data ? asUpdate(data) : null }
export async function listPreviousUpdateCandidates(client: DatabaseClient, topicId: string, before?: string): Promise<NewsUpdate[]> { let query = client.from('news_updates').select(detailFields).eq('topic_id', topicId).order('created_at', { ascending: false }); if (before) query = query.lt('created_at', before); const { data, error } = await query; if (error) throw new Error('이전 업데이트 후보를 불러오지 못했습니다.'); return data.map(asUpdate) }
export async function listAssignableSources(client: DatabaseClient, postId: string, updateId?: string): Promise<AssignableSource[]> { let query = client.from('sources').select('id, source_name, source_title, source_url, news_update_id').eq('post_id', postId).order('sort_order'); if (updateId) query = query.or(`news_update_id.is.null,news_update_id.eq.${updateId}`); else query = query.is('news_update_id', null); const { data, error } = await query; if (error) throw new Error('연결 가능한 출처를 불러오지 못했습니다.'); return data }
export async function createNewsUpdate(client: DatabaseClient, input: CreateNewsUpdateInput): Promise<NewsUpdateRow> { const { data, error } = await client.rpc('create_news_update', { p_post_id: input.postId, p_topic_id: input.topicId, p_update_type: input.updateType, p_headline: input.headline, p_fact_summary: input.factSummary, p_importance_summary: input.importanceSummary!, p_impact_summary: input.impactSummary!, p_change_summary: input.changeSummary!, p_previous_update_id: input.previousUpdateId!, p_source_ids: input.sourceIds }); if (error) throwUpdateError(error); return data as NewsUpdateRow }
export async function updateNewsUpdate(client: DatabaseClient, id: string, input: SaveNewsUpdateInput): Promise<NewsUpdateRow> { const { data, error } = await client.rpc('update_news_update', { p_update_id: id, p_headline: input.headline, p_fact_summary: input.factSummary, p_importance_summary: input.importanceSummary!, p_impact_summary: input.impactSummary!, p_change_summary: input.changeSummary!, p_previous_update_id: input.previousUpdateId!, p_source_ids: input.sourceIds }); if (error) throwUpdateError(error); return data as NewsUpdateRow }
export async function reorderNewsUpdates(client: DatabaseClient, postId: string, ids: string[]): Promise<void> { const { error } = await client.rpc('reorder_news_updates', { p_post_id: postId, p_update_ids: ids }); if (error) throwUpdateError(error) }

