import { describe, expect, it, vi } from 'vitest'
import { preparePublicationPlan } from './publicationPlan'
import type { CallerDatabase, SourceContent, TaxonomyCatalog, TaxonomyMapping } from './schemas'
import type { PublicationWordPressClient } from './wordpressClient'

const tagNames = ['A', 'B', 'C', 'D', 'E']
const content: SourceContent = { id: crypto.randomUUID(), categoryId: 'economy', categoryName: '경제', contentGroup: 'news', wrapperClass: 'daily-brief-note news-briefing economy', slugPattern: 'economy-briefing-YYYY-MM-DD', seriesNo: null, briefingDate: '2026-07-18', publishedOn: null, contentStatus: 'ready', updatedAt: '2026-07-18T00:00:00Z', representativeTitle: '대표 제목', metaDescription: '가'.repeat(130), htmlBody: '<div class="daily-brief-note news-briefing economy"><h1>대표 제목</h1><a href="#sources">출처</a></div>', slug: 'economy-briefing-2026-07-18', tags: tagNames.map((name) => ({ id: crypto.randomUUID(), name, normalizedName: name.toLowerCase() })) }
const catalog: TaxonomyCatalog = { categories: [{ id: 1, name: '경제', slug: 'economy', parent: 0, count: 0 }], tags: tagNames.map((name, index) => ({ id: index + 10, name, slug: name, count: 0 })), categoryPages: 1, tagPages: 1 }
const mappings: TaxonomyMapping[] = []
const database = (overrides: Partial<CallerDatabase> = {}): CallerDatabase => ({ loadContent: vi.fn(async () => content), readContentUpdatedAt: vi.fn(async () => content.updatedAt), loadMappings: vi.fn(async () => mappings), ...overrides })
const wordpress = (matches: Array<{ id: number; slug: string; status: string; modifiedGmt: string | null; link: string | null }> = []): PublicationWordPressClient => ({ getCatalogPage: vi.fn(), getStatuses: vi.fn(async () => ['draft', 'pending', 'publish', 'future', 'private']), findPostsBySlug: vi.fn(async () => matches) })

describe('publication plan', () => {
  it('ready dry-run plan을 만든다', async () => { const plan = await preparePublicationPlan({ database: database(), wordpress: wordpress(), catalog, siteOrigin: 'https://example.com', contentId: content.id, now: () => new Date('2026-07-18T01:00:00Z') }); expect(plan).toMatchObject({ ok: true, mode: 'dry-run', writePerformed: false, readyForDraftCreation: true, checkedAt: '2026-07-18T01:00:00.000Z' }); expect(plan?.payload.status).toBe('draft') })
  it('missing tag는 plan 성공과 readiness를 구분한다', async () => { const plan = await preparePublicationPlan({ database: database(), wordpress: wordpress(), catalog: { ...catalog, tags: catalog.tags.slice(0, 4) }, siteOrigin: 'https://example.com', contentId: content.id }); expect(plan?.ok).toBe(true); expect(plan?.readyForDraftCreation).toBe(false); expect(plan?.blockers.some((item) => item.code === 'TAG_MAPPING_MISSING')).toBe(true) })
  it('WordPress duplicate slug를 차단한다', async () => { const plan = await preparePublicationPlan({ database: database(), wordpress: wordpress([{ id: 9, slug: content.slug, status: 'draft', modifiedGmt: null, link: 'https://example.com/?p=9' }]), catalog, siteOrigin: 'https://example.com', contentId: content.id }); expect(plan?.blockers.some((item) => item.code === 'WORDPRESS_DUPLICATE_SLUG')).toBe(true) })
  it('복수 duplicate를 inconsistent로 분류한다', async () => { const plan = await preparePublicationPlan({ database: database(), wordpress: wordpress([{ id: 9, slug: content.slug, status: 'draft', modifiedGmt: null, link: null }, { id: 10, slug: content.slug, status: 'draft', modifiedGmt: null, link: null }]), catalog, siteOrigin: 'https://example.com', contentId: content.id }); expect(plan?.blockers.some((item) => item.code === 'WORDPRESS_DUPLICATE_INCONSISTENT')).toBe(true) })
  it('preview 도중 updated_at 변경을 차단한다', async () => { const plan = await preparePublicationPlan({ database: database({ readContentUpdatedAt: vi.fn(async () => '2026-07-18T02:00:00Z') }), wordpress: wordpress(), catalog, siteOrigin: 'https://example.com', contentId: content.id }); expect(plan?.blockers.some((item) => item.code === 'CONTENT_UPDATED_DURING_PREVIEW')).toBe(true) })
  it('missing/RLS-hidden content는 null이다', async () => expect(preparePublicationPlan({ database: database({ loadContent: vi.fn(async () => null) }), wordpress: wordpress(), catalog, siteOrigin: 'https://example.com', contentId: content.id })).resolves.toBeNull())
  it('checkedAt은 fingerprint에 영향을 주지 않는다', async () => { const one = await preparePublicationPlan({ database: database(), wordpress: wordpress(), catalog, siteOrigin: 'https://example.com', contentId: content.id, now: () => new Date(0) }); const two = await preparePublicationPlan({ database: database(), wordpress: wordpress(), catalog, siteOrigin: 'https://example.com', contentId: content.id, now: () => new Date(1000) }); expect(one?.payloadFingerprint).toBe(two?.payloadFingerprint) })
  it('owner ID나 credential을 응답하지 않는다', async () => { const plan = await preparePublicationPlan({ database: database(), wordpress: wordpress(), catalog, siteOrigin: 'https://example.com', contentId: content.id }); const serialized = JSON.stringify(plan); expect(serialized).not.toMatch(/ownerId|owner_id|authorization|password/i) })
  it('blocker와 warning 순서는 deterministic하다', async () => { const plan = await preparePublicationPlan({ database: database({ loadContent: vi.fn(async () => ({ ...content, representativeTitle: null, metaDescription: '짧음' })) }), wordpress: wordpress(), catalog: { ...catalog, tags: [] }, siteOrigin: 'https://example.com', contentId: content.id }); expect(plan?.blockers.map((item) => item.code)).toEqual([...plan!.blockers.map((item) => item.code)].sort()) })
})
