import { QueryClient, QueryClientProvider } from '@tanstack/react-query'
import { render, screen, waitFor } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { MemoryRouter } from 'react-router-dom'
import { beforeEach, describe, expect, it, vi } from 'vitest'
import type { RestoreJobDetail, RestoreJobRecord } from '../features/backups/restoreExecution.types'
import { BackupRestoreJobDetailPageContent } from './BackupRestoreJobDetailPage'

const mocks = vi.hoisted(() => ({ jobQuery: vi.fn(), recordsQuery: vi.fn(), cancelHook: vi.fn(), resumeHook: vi.fn(), getRecords: vi.fn(), execute: vi.fn(), copy: vi.fn(), cancel: vi.fn(), resume: vi.fn() }))
vi.mock('../features/backups/restoreExecution.queries', () => ({
  restoreJobQueryKeys: { all: ['restore-jobs'] }, useRestoreJobQuery: mocks.jobQuery, useRestoreJobRecordsQuery: mocks.recordsQuery,
  useCancelRestoreJobMutation: mocks.cancelHook, useResumeRestoreJobMutation: mocks.resumeHook,
}))
vi.mock('../features/backups/restoreExecution.repository', () => ({ getRestoreJobRecords: mocks.getRecords }))
vi.mock('../features/backups/executeRestoreJob', () => ({ executeRestoreRecords: mocks.execute }))
vi.mock('../features/briefingPrompts/copyTextToClipboard', () => ({ copyTextToClipboard: mocks.copy }))

const id = '00000000-0000-4000-8000-000000000001'
const postId = '00000000-0000-4000-8000-000000000002'
const job: RestoreJobDetail = { id, sourceName: 'backup.json', backupProfile: 'core', backupChecksum: 'a'.repeat(64), planFingerprint: 'b'.repeat(64), status: 'ready', currentStageKey: 'posts', totalCount: 4, pendingCount: 1, runningCount: 0, appliedCount: 1, reusedCount: 1, skippedCount: 1, failedCount: 1, cancelledCount: 0, retryableFailureCount: 1, completedStageCount: 1, stageCount: 2, progressPercent: 100, stageProgressPercent: 50, createdAt: '2026-07-15T00:00:00Z', startedAt: null, completedAt: null, backupFormat: 'daily-brief-note-backup', backupSchemaVersion: 1, planFormat: 'daily-brief-note-restore-plan', planSchemaVersion: 1, planVersion: 1, analysisFingerprint: 'c'.repeat(64), policies: { timestamps: 'preserve' }, categoryMappings: [], executionStages: [] }
function record(overrides: Partial<RestoreJobRecord> = {}): RestoreJobRecord { return { id: postId, section: 'posts', sourceId: 'source-post', targetId: postId, action: 'preserve_id', stageKey: 'posts', stageOrder: 2, sequenceNo: 0, safeDisplay: '복원 게시물', status: 'applied', attemptCount: 1, errorCode: null, errorMessage: null, retryable: false, startedAt: '2026-07-15T00:00:00Z', completedAt: '2026-07-15T00:00:01Z', attempts: [], ...overrides } }
const jobRefetch = vi.fn().mockResolvedValue(undefined); const recordsRefetch = vi.fn().mockResolvedValue(undefined)
function view() { const queryClient = new QueryClient({ defaultOptions: { queries: { retry: false }, mutations: { retry: false } } }); return render(<QueryClientProvider client={queryClient}><MemoryRouter><BackupRestoreJobDetailPageContent client={{} as never} userId="owner" jobId={id} /></MemoryRouter></QueryClientProvider>) }

describe('BackupRestoreJobDetailPage', () => {
  beforeEach(() => {
    vi.clearAllMocks(); mocks.jobQuery.mockReturnValue({ isPending: false, isError: false, data: job, refetch: jobRefetch }); mocks.recordsQuery.mockReturnValue({ isPending: false, isError: false, data: [record()], refetch: recordsRefetch }); mocks.cancelHook.mockReturnValue({ mutateAsync: mocks.cancel }); mocks.resumeHook.mockReturnValue({ mutateAsync: mocks.resume }); mocks.getRecords.mockResolvedValue([]); mocks.execute.mockResolvedValue({ processed: 0 }); mocks.copy.mockResolvedValue(undefined); mocks.cancel.mockResolvedValue(undefined); mocks.resume.mockResolvedValue(undefined); vi.spyOn(window, 'confirm').mockReturnValue(true)
  })
  it('DB 집계 진행률과 현재 stage를 표시한다', () => { view(); expect(screen.getByText('진행률', { selector: 'dt' }).nextSibling).toHaveTextContent('100%'); expect(screen.getByText('현재 stage', { selector: 'dt' }).nextSibling).toHaveTextContent('posts') })
  it('applied·reused·skipped·failed 결과 수를 표시한다', () => { view(); for (const label of ['applied', 'reused', 'skipped', 'failed']) expect(screen.getByText(label, { selector: 'dt' }).nextSibling).toHaveTextContent('1') })
  it('job metadata와 정책을 표시한다', async () => { view(); expect(screen.getByText(/daily-brief-note-backup v1/)).toBeInTheDocument(); await userEvent.click(screen.getByText('정책')); expect(screen.getByText(/timestamps/)).toBeInTheDocument() })
  it('record 상태·action·attempt와 안전한 오류를 표시한다', () => { mocks.recordsQuery.mockReturnValue({ isPending: false, isError: false, data: [record({ status: 'failed', action: 'remap_id', attemptCount: 2, errorCode: 'RESTORE_UNIQUE_KEY_CONFLICT', errorMessage: '안전한 오류' })], refetch: recordsRefetch }); view(); expect(screen.getByText(/posts \/ remap_id/)).toBeInTheDocument(); expect(screen.getByText(/attempt 2/)).toHaveTextContent('안전한 오류') })
  it('성공 posts record에 생성 게시물 링크를 표시한다', () => { view(); expect(screen.getByRole('link', { name: '게시물 열기' })).toHaveAttribute('href', `/content/${postId}`) })
  it('payload와 HTML 전문을 기본 렌더링하지 않는다', () => { view(); expect(document.body.textContent).not.toContain('htmlBody'); expect(document.body.innerHTML).not.toContain('&lt;article') })
  it.each([
    ['stage', 'posts', { stage: 'posts' }], ['section', 'seoData', { section: 'seoData' }], ['action', 'reuse_existing', { action: 'reuse_existing' }], ['status', 'failed', { status: 'failed' }], ['retryable', 'true', { retryable: true }], ['검색', '복원', { search: '복원' }],
  ] as const)('%s filter를 query 인수에 반영한다', async (label, value, expected) => { view(); const field = screen.getByLabelText(label); if (field instanceof HTMLSelectElement) await userEvent.selectOptions(field, value); else await userEvent.type(field, value); await waitFor(() => expect(mocks.recordsQuery).toHaveBeenLastCalledWith(expect.anything(), 'owner', id, expect.objectContaining(expected))) })
  it('첫 실행은 pending mode로 orchestration을 시작한다', async () => { mocks.getRecords.mockResolvedValue([]); view(); await userEvent.click(screen.getByRole('button', { name: '실행 시작' })); await waitFor(() => expect(mocks.execute).toHaveBeenCalledWith(expect.anything(), [], 'pending', expect.anything())) })
  it('실행 중 버튼과 입력을 잠근다', async () => { let resolve!: (value: { processed: number }) => void; mocks.getRecords.mockResolvedValue([record({ status: 'pending' })]); mocks.execute.mockReturnValue(new Promise((done) => { resolve = done })); view(); await userEvent.click(screen.getByRole('button', { name: '실행 시작' })); expect(screen.getByRole('button', { name: '실행 시작' })).toBeDisabled(); resolve({ processed: 0 }) })
  it('네트워크 응답 유실 시 안전한 재조회 안내를 표시한다', async () => { mocks.getRecords.mockRejectedValueOnce(new Error('raw owner_id')); view(); await userEvent.click(screen.getByRole('button', { name: '실행 시작' })); expect(await screen.findByRole('status')).toHaveTextContent('네트워크 응답을 확정할 수 없어') })
  it('retryable 실패를 failed mode로 재시도한다', async () => { mocks.getRecords.mockResolvedValue([record({ status: 'failed', retryable: true })]); view(); await userEvent.click(screen.getByRole('button', { name: '현재 stage 실패 재시도' })); await waitFor(() => expect(mocks.execute).toHaveBeenCalledWith(expect.anything(), expect.anything(), 'failed', expect.anything())) })
  it('취소 confirmation을 거절하면 RPC를 호출하지 않는다', async () => { vi.mocked(window.confirm).mockReturnValue(false); view(); await userEvent.click(screen.getByRole('button', { name: '작업 취소' })); expect(mocks.cancel).not.toHaveBeenCalled() })
  it('취소 confirmation에 rollback 아님과 성공 row 유지를 알린다', async () => { view(); await userEvent.click(screen.getByRole('button', { name: '작업 취소' })); expect(window.confirm).toHaveBeenCalledWith(expect.stringMatching(/rollback.*이미 복원된 row는 유지/)); expect(mocks.cancel).toHaveBeenCalled() })
  it('cancelled job만 재개 버튼을 활성화한다', async () => { mocks.jobQuery.mockReturnValue({ isPending: false, isError: false, data: { ...job, status: 'cancelled' }, refetch: jobRefetch }); view(); const button = screen.getByRole('button', { name: '취소 작업 재개' }); expect(button).toBeEnabled(); await userEvent.click(button); expect(mocks.resume).toHaveBeenCalled() })
  it('stale 재개 실패를 안전하게 표시한다', async () => { mocks.jobQuery.mockReturnValue({ isPending: false, isError: false, data: { ...job, status: 'cancelled' }, refetch: jobRefetch }); mocks.resume.mockRejectedValue(new Error('RESTORE_PLAN_STALE raw')); view(); await userEvent.click(screen.getByRole('button', { name: '취소 작업 재개' })); expect(await screen.findByRole('status')).toHaveTextContent('DB 상태가 변경되어') })
  it('결과 JSON을 payload 없는 조회 결과로 복사한다', async () => { mocks.getRecords.mockResolvedValue([record()]); view(); await userEvent.click(screen.getByRole('button', { name: '결과 JSON 복사' })); expect(mocks.copy).toHaveBeenCalledWith(expect.stringContaining('backup.json')); expect(mocks.copy.mock.calls[0][0]).not.toContain('htmlBody') })
  it('실패 목록을 plain text로 복사한다', async () => { mocks.getRecords.mockResolvedValue([record({ status: 'failed', errorCode: 'RESTORE_SAFE', errorMessage: '안전한 오류' }), record()]); view(); await userEvent.click(screen.getByRole('button', { name: '실패 목록 복사' })); expect(mocks.copy).toHaveBeenCalledWith(expect.stringMatching(/^posts\/posts 복원 게시물: RESTORE_SAFE 안전한 오류$/)) })
  it('loading·error·not found 상태를 안전하게 렌더링한다', () => { mocks.jobQuery.mockReturnValue({ isPending: true }); const first = view(); expect(screen.getByRole('status')).toBeInTheDocument(); first.unmount(); mocks.jobQuery.mockReturnValue({ isPending: false, isError: true }); view(); expect(screen.getByRole('alert')).toBeInTheDocument() })
})
