import { Link, useParams } from 'react-router-dom'
import { useAuth } from '../features/auth/useAuth'
import { useNewsUpdateQuery } from '../features/newsUpdates/newsUpdates.queries'
import { newsUpdateTypeLabels, type NewsUpdateType } from '../features/newsUpdates/newsUpdates.types'
import { formatUpdatedAt } from '../features/posts/postFormatters'
import { supabase, type DatabaseClient } from '../shared/supabase/client'
export function NewsUpdateDetailPageContent({ client = supabase, userId, updateId }: { client?: DatabaseClient | null; userId: string; updateId: string }) { const query = useNewsUpdateQuery(client, userId, updateId); if (query.isPending) return <div className="content-state" role="status">뉴스 항목을 불러오고 있습니다.</div>; if (query.isError) return <div className="content-state content-state--error" role="alert"><h1>뉴스 항목을 불러오지 못했습니다</h1></div>; const item = query.data; if (!item) return <section className="not-found"><h1>뉴스 항목을 찾을 수 없습니다</h1><Link to="/content">콘텐츠 목록으로</Link></section>; return <article className="content-detail"><div className="page-heading-with-actions"><div><p className="dashboard__eyebrow">{newsUpdateTypeLabels[item.update_type as NewsUpdateType] ?? item.update_type}</p><h1>{item.headline}</h1></div><span className="status-badge">#{item.item_order}</span></div><dl className="content-detail__metadata"><div className="content-detail__wide"><dt>게시물</dt><dd><Link to={`/content/${item.post.id}`}>{item.post.display_id ?? item.post.title}</Link></dd></div><div className="content-detail__wide"><dt>뉴스 주제</dt><dd><Link to={`/news-topics/${item.topic.id}`}>{item.topic.canonical_title}</Link></dd></div><div><dt>유형</dt><dd>{newsUpdateTypeLabels[item.update_type as NewsUpdateType] ?? item.update_type}</dd></div><div><dt>표시 순서</dt><dd>{item.item_order}</dd></div><div><dt>생성일</dt><dd>{formatUpdatedAt(item.created_at)}</dd></div><div><dt>수정일</dt><dd>{formatUpdatedAt(item.updated_at)}</dd></div></dl>{[['확인된 사실', item.fact_summary], ['중요성', item.importance_summary], ['영향', item.impact_summary], ['이전 대비 변화', item.change_summary]].map(([title, body]) => <section key={title} className="content-detail__section"><h2>{title}</h2><p>{body || '미입력'}</p></section>)}<section className="content-detail__section"><h2>이전 업데이트</h2>{item.previous_update_id ? <Link to={`/news-updates/${item.previous_update_id}`}>이전 업데이트 보기</Link> : <p className="field-help">연결 없음</p>}</section><section className="content-detail__section"><h2>연결 출처 ({item.sources.length}개)</h2><ul className="detail-source-list">{item.sources.map((source) => <li key={source.id}><strong>{source.source_name}</strong><p>{source.source_title}</p><a href={source.source_url} target="_blank" rel="noopener noreferrer">{source.source_url}</a></li>)}</ul></section><div className="detail-actions"><Link className="secondary-link" to={`/content/${item.post.id}`}>게시물로 돌아가기</Link><Link className="secondary-link" to={`/news-topics/${item.topic.id}`}>주제로 이동</Link><Link className="primary-link primary-link--inline" to={`/news-updates/${item.id}/edit`}>수정</Link></div></article> }
export function NewsUpdateDetailPage() { const { user } = useAuth(); const { updateId = '' } = useParams(); return <NewsUpdateDetailPageContent userId={user?.id ?? ''} updateId={updateId} /> }

