import { useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { useAuth } from '../features/auth/useAuth'
import { useNewsTopicsQuery } from '../features/newsTopics/newsTopics.queries'
import { NewsUpdateForm } from '../features/newsUpdates/NewsUpdateForm'
import type { NewsUpdateFormValues } from '../features/newsUpdates/newsUpdateFormSchema'
import { useAssignableSourcesQuery, useNewsUpdateQuery, usePreviousUpdatesQuery, useUpdateNewsUpdateMutation } from '../features/newsUpdates/newsUpdates.queries'
import { supabase, type DatabaseClient } from '../shared/supabase/client'
export function NewsUpdateEditPageContent({ client = supabase, userId, updateId }: { client?: DatabaseClient | null; userId: string; updateId: string }) { const navigate = useNavigate(); const [error, setError] = useState<string | null>(null); const itemQuery = useNewsUpdateQuery(client, userId, updateId); const topicsQuery = useNewsTopicsQuery(client, userId); const item = itemQuery.data; const previousQuery = usePreviousUpdatesQuery(client, userId, item?.topic_id ?? '', item?.created_at); const sourcesQuery = useAssignableSourcesQuery(client, userId, item?.post_id ?? '', updateId); const mutation = useUpdateNewsUpdateMutation(client, userId, { id: updateId, postId: item?.post_id ?? '', topicId: item?.topic_id ?? '' }); if (itemQuery.isPending || topicsQuery.isPending || sourcesQuery.isPending) return <div className="content-state" role="status">뉴스 항목 편집기를 불러오고 있습니다.</div>; if (!item) return <section className="not-found"><h1>뉴스 항목을 찾을 수 없습니다</h1><Link to="/content">콘텐츠 목록으로</Link></section>; const initial: NewsUpdateFormValues = { topicId: item.topic_id, updateType: item.update_type as NewsUpdateFormValues['updateType'], headline: item.headline, factSummary: item.fact_summary, importanceSummary: item.importance_summary ?? '', impactSummary: item.impact_summary ?? '', changeSummary: item.change_summary ?? '', previousUpdateId: item.previous_update_id ?? '', sourceIds: item.sources.map((source) => source.id) }; async function submit(values: NewsUpdateFormValues) { setError(null); try { await mutation.mutateAsync({ headline: values.headline.trim(), factSummary: values.factSummary.trim(), importanceSummary: values.importanceSummary.trim() || null, impactSummary: values.impactSummary.trim() || null, changeSummary: values.changeSummary.trim() || null, previousUpdateId: values.previousUpdateId || null, sourceIds: values.sourceIds }); navigate(`/news-updates/${updateId}`) } catch (cause) { setError(cause instanceof Error ? cause.message : '뉴스 항목 저장 중 오류가 발생했습니다.') } } return <article className="content-detail"><p className="dashboard__eyebrow">뉴스 항목</p><h1>뉴스 항목 수정</h1><NewsUpdateForm editing post={{ category_id: item.topic.category_id, title: item.post.title, display_id: item.post.display_id }} topics={topicsQuery.data ?? []} previous={previousQuery.data ?? []} sources={sourcesQuery.data ?? []} initial={initial} pending={mutation.isPending} error={error} onSubmit={submit} /></article> }
export function NewsUpdateEditPage() { const { user } = useAuth(); const { updateId = '' } = useParams(); return <NewsUpdateEditPageContent userId={user?.id ?? ''} updateId={updateId} /> }
