import { useCallback, useState } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { useAuth } from '../features/auth/useAuth'
import { useNewsTopicsQuery } from '../features/newsTopics/newsTopics.queries'
import { useAssignableSourcesQuery, useCreateNewsUpdateMutation, usePreviousUpdatesQuery } from '../features/newsUpdates/newsUpdates.queries'
import { NewsUpdateForm } from '../features/newsUpdates/NewsUpdateForm'
import type { NewsUpdateFormValues } from '../features/newsUpdates/newsUpdateFormSchema'
import { useActiveCategoriesQuery } from '../features/categories/categories.queries'
import { usePostQuery } from '../features/posts/posts.queries'
import { supabase, type DatabaseClient } from '../shared/supabase/client'
export function NewsUpdateCreatePageContent({ client = supabase, userId, postId }: { client?: DatabaseClient | null; userId: string; postId: string }) { const navigate = useNavigate(); const [topicId, setTopicId] = useState(''); const [error, setError] = useState<string | null>(null); const postQuery = usePostQuery(client, userId, postId); const topicsQuery = useNewsTopicsQuery(client, userId); const categoriesQuery = useActiveCategoriesQuery(client); const sourcesQuery = useAssignableSourcesQuery(client, userId, postId); const previousQuery = usePreviousUpdatesQuery(client, userId, topicId); const mutation = useCreateNewsUpdateMutation(client, userId); const onTopicChange = useCallback((id: string) => setTopicId(id), []); if (postQuery.isPending || topicsQuery.isPending || categoriesQuery.isPending || sourcesQuery.isPending) return <div className="content-state" role="status">뉴스 항목 편집기를 불러오고 있습니다.</div>; const post = postQuery.data; const category = categoriesQuery.data?.find((item) => item.id === post?.category_id); if (!post || category?.content_group !== 'news') return <section className="not-found"><h1>뉴스 게시물을 찾을 수 없습니다</h1><Link to="/content">콘텐츠 목록으로</Link></section>; async function submit(values: NewsUpdateFormValues) { setError(null); try { const saved = await mutation.mutateAsync({ postId, topicId: values.topicId, updateType: values.updateType, headline: values.headline.trim(), factSummary: values.factSummary.trim(), importanceSummary: values.importanceSummary.trim() || null, impactSummary: values.impactSummary.trim() || null, changeSummary: values.changeSummary.trim() || null, previousUpdateId: values.previousUpdateId || null, sourceIds: values.sourceIds }); navigate(`/news-updates/${saved.id}`) } catch (cause) { setError(cause instanceof Error ? cause.message : '뉴스 항목 저장 중 오류가 발생했습니다.') } } return <article className="content-detail"><p className="dashboard__eyebrow">뉴스 항목</p><h1>뉴스 항목 추가</h1><NewsUpdateForm post={post} topics={(topicsQuery.data ?? []).filter((topic) => topic.category_id === post.category_id)} previous={previousQuery.data ?? []} sources={sourcesQuery.data ?? []} pending={mutation.isPending} error={error} onTopicChange={onTopicChange} onSubmit={submit} /></article> }
export function NewsUpdateCreatePage() { const { user } = useAuth(); const { postId = '' } = useParams(); return <NewsUpdateCreatePageContent userId={user?.id ?? ''} postId={postId} /> }

