import { describe, expect, it, vi } from 'vitest'
import type { DatabaseClient } from '../../shared/supabase/client'
import { createNewsTopic, getNewsTopicById, listNewsTopics, listNewsTopicStatusHistory, transitionNewsTopicStatus, updateNewsTopic } from './newsTopics.repository'
import type { NewsTopic } from './newsTopics.types'

const topic: NewsTopic = { id: 'topic-1', category_id: 'economy', topic_key: 'rate-outlook', canonical_title: '금리 전망', topic_summary: null, status: 'active', closed_reason: null, first_seen_at: '2026-07-01', last_seen_at: '2026-07-01', created_at: '2026-07-01T00:00:00Z', updated_at: '2026-07-01T00:00:00Z' }
function chain(result: unknown) { const b = { select: vi.fn(), order: vi.fn(), eq: vi.fn(), maybeSingle: vi.fn(), insert: vi.fn(), update: vi.fn(), single: vi.fn() }; b.select.mockReturnValue(b); b.order.mockReturnValueOnce(b).mockResolvedValueOnce(result); b.eq.mockReturnValue(b); b.maybeSingle.mockResolvedValue(result); b.insert.mockReturnValue(b); b.update.mockReturnValue(b); b.single.mockResolvedValue(result); return b }

describe('newsTopics repository', () => {
  it('lists only explicit fields in descending date order', async () => { const b = chain({ data: [topic], error: null }); const client = { from: vi.fn(() => b) } as unknown as DatabaseClient; await expect(listNewsTopics(client)).resolves.toEqual([topic]); expect(b.select).toHaveBeenCalledWith(expect.not.stringContaining('*')); expect(b.order).toHaveBeenNthCalledWith(1, 'last_seen_at', { ascending: false }) })
  it('returns null for an invalid topic id', async () => { const b = chain({ data: null, error: { code: '22P02' } }); const client = { from: vi.fn(() => b) } as unknown as DatabaseClient; await expect(getNewsTopicById(client, 'bad')).resolves.toBeNull() })
  it('normalizes a created topic key', async () => { const b = chain({ data: topic, error: null }); const client = { from: vi.fn(() => b) } as unknown as DatabaseClient; await createNewsTopic(client, { ownerId: 'owner', categoryId: 'economy', topicKey: ' RATE-OUTLOOK ', canonicalTitle: '금리 전망', topicSummary: null, initialStatus: 'active', firstSeenAt: '2026-07-01', lastSeenAt: '2026-07-01' }); expect(b.insert).toHaveBeenCalledWith(expect.objectContaining({ topic_key: 'rate-outlook', owner_id: 'owner' })) })
  it('maps duplicate keys to a Korean error', async () => { const b = chain({ data: null, error: { code: '23505', message: 'topic_key' } }); const client = { from: vi.fn(() => b) } as unknown as DatabaseClient; await expect(createNewsTopic(client, { ownerId: 'owner', categoryId: 'economy', topicKey: 'rate', canonicalTitle: 'Title', topicSummary: null, initialStatus: 'active', firstSeenAt: '2026-07-01', lastSeenAt: '2026-07-01' })).rejects.toThrow('동일한 주제 키') })
  it('updates only editable fields', async () => { const b = chain({ data: topic, error: null }); const client = { from: vi.fn(() => b) } as unknown as DatabaseClient; await updateNewsTopic(client, topic.id, { canonicalTitle: '수정', topicSummary: null, lastSeenAt: '2026-07-02' }); expect(b.update).toHaveBeenCalledWith({ canonical_title: '수정', topic_summary: null, last_seen_at: '2026-07-02' }) })
  it('uses RPC for transitions and newest-first history', async () => { const b = chain({ data: [], error: null }); const rpc = vi.fn().mockResolvedValue({ data: topic, error: null }); const client = { from: vi.fn(() => b), rpc } as unknown as DatabaseClient; await transitionNewsTopicStatus(client, topic.id, { targetStatus: 'monitoring', reason: null }); await listNewsTopicStatusHistory(client, topic.id); expect(rpc).toHaveBeenCalledWith('transition_news_topic_status', expect.objectContaining({ p_target_status: 'monitoring' })); expect(b.order).toHaveBeenCalledWith('changed_at', { ascending: false }) })
})
