import { beforeEach, describe, expect, it, vi } from 'vitest'
import type { DatabaseClient } from '../../shared/supabase/client'
import { buildPreparedImportItems, prepareImportJob } from './prepareImportJob'
import type { ImportCategory, ImportItemValidationResult, ImportValidationResult } from './importValidation.types'

const createMock = vi.hoisted(() => vi.fn())
const appendMock = vi.hoisted(() => vi.fn())
const finalizeMock = vi.hoisted(() => vi.fn())
vi.mock('./importJobs.repository', () => ({ createOrGetImportJob: createMock, appendImportJobItems: appendMock, finalizeImportJob: finalizeMock }))

const client = {} as DatabaseClient
const categories: ImportCategory[] = [{ id: 'economy', contentGroup: 'news', name: '경제', code: 'ECO', wrapperClass: 'daily-brief-note news-briefing economy', displayIdPattern: '#YYYY-MM-DD-ECO', slugPattern: 'economy-briefing-YYYY-MM-DD', enabled: true }]
function validation(index: number, status: 'ready' | 'warning' = 'ready'): ImportItemValidationResult {
  return { index, externalKey: `item-${index}`, title: `Item ${index}`, categoryId: 'economy', publishedOn: '2027-01-01', status, issues: [], normalizedPreview: { externalKey: `item-${index}`, categoryId: 'economy', title: `Item ${index}`, slug: `item-${index}`, status: 'draft', publishedOn: null, briefingDate: '2027-01-01', displayId: '#2027-01-01-ECO', seriesNo: null, wordpressUrl: null, tags: [], sources: [], metadata: null, newsTracking: { present: false, topicCount: 0, updateCount: 0, followupCount: 0 }, htmlBody: { present: false, length: 0, checksum: null } } }
}
function raw(index: number, tracking = false) { return { externalKey: `item-${index}`, categoryId: 'economy', title: `Item ${index}`, summary: 'Summary', slug: `economy-briefing-2027-01-${String(index + 1).padStart(2, '0')}`, status: 'draft', briefingDate: `2027-01-${String(index + 1).padStart(2, '0')}`, displayId: `#2027-01-${String(index + 1).padStart(2, '0')}-ECO`, seo: {}, image: {}, tags: [], sources: [], metadata: null, newsTracking: tracking ? { topics: [{ topicExternalKey: 'topic-a', topicKey: 'topic-a', canonicalTitle: 'Topic', topicSummary: null, status: 'active', closedReason: null, firstSeenAt: '2027-01-01', lastSeenAt: '2027-01-01' }], updates: [{ updateExternalKey: 'update-a', topicExternalKey: 'topic-a', updateType: 'new', headline: 'Headline', factSummary: 'Facts', importanceSummary: null, impactSummary: null, changeSummary: null, previousUpdateExternalKey: null, itemOrder: 1, sourceOrders: [1] }], followups: [] } : null } }
function result(count: number): ImportValidationResult { return { validationVersion: 1, status: 'valid', schemaVersion: 1, databaseCheck: 'complete', summary: { total: count, ready: count, warning: 0, invalid: 0, duplicate: 0, exactDuplicate: 0, possibleDuplicate: 0 }, bundleIssues: [], items: Array.from({ length: count }, (_, index) => validation(index)) } }

describe('buildPreparedImportItems', () => {
  it('콘텐츠 실행 payload와 fingerprint를 만든다', async () => { const [prepared] = await buildPreparedImportItems({ items: [validation(0)], rawItems: [raw(0)], categories, approvedWarnings: new Set() }); expect(prepared.normalizedPayload.content.category_id).toBe('economy'); expect(prepared.payloadFingerprint).toMatch(/^[0-9a-f]{64}$/) })
  it('newsTracking을 콘텐츠 payload에서 분리한다', async () => { const [prepared] = await buildPreparedImportItems({ items: [validation(0)], rawItems: [raw(0, true)], categories, approvedWarnings: new Set() }); expect(prepared.normalizedPayload.content).not.toHaveProperty('newsTracking'); expect(prepared.normalizedPayload.tracking).toMatchObject({ topics: [expect.objectContaining({ topic_external_key: 'topic-a' })] }) })
  it('tracking이 없으면 snapshot에 null을 보존한다', async () => { const [prepared] = await buildPreparedImportItems({ items: [validation(0)], rawItems: [raw(0)], categories, approvedWarnings: new Set() }); expect(prepared.normalizedPayload.tracking).toBeNull() })
  it('warning 승인 상태를 snapshot 등록 정보에 기록한다', async () => { const row = validation(0, 'warning'); const [prepared] = await buildPreparedImportItems({ items: [row], rawItems: [raw(0)], categories, approvedWarnings: new Set(['external:item-0']) }); expect(prepared.validationStatus).toBe('warning'); expect(prepared.warningAcknowledged).toBe(true) })
  it('legacy validation mode를 불변 content snapshot에 기록한다', async () => { const [prepared] = await buildPreparedImportItems({ items: [validation(0)], rawItems: [raw(0)], categories, approvedWarnings: new Set(), validationMode: 'legacy' }); expect(prepared.normalizedPayload.content.validation_mode).toBe('legacy') })
  it('배열 입력 순서를 itemIndex로 보존한다', async () => { const prepared = await buildPreparedImportItems({ items: [validation(2), validation(0)], rawItems: [raw(2), raw(0)], categories, approvedWarnings: new Set() }); expect(prepared.map((item) => item.itemIndex)).toEqual([0, 1]) })
})

describe('prepareImportJob', () => {
  beforeEach(() => { createMock.mockReset().mockResolvedValue({ jobId: '00000000-0000-0000-0000-000000000001', isExisting: false, status: 'preparing' }); appendMock.mockReset().mockResolvedValue({ appendedCount: 1, existingCount: 0, storedCount: 1 }); finalizeMock.mockReset().mockResolvedValue({ jobId: '00000000-0000-0000-0000-000000000001', status: 'ready', itemCount: 1, idempotent: false }) })
  it('create → append → finalize 순서로 준비한다', async () => { await prepareImportJob(client, { format: 'daily-brief-note-content-import', schemaVersion: 1, sourceName: 'one.json', validationResult: result(1), items: [validation(0)], rawItems: [raw(0)], categories, approvedWarnings: new Set() }); expect(createMock.mock.invocationCallOrder[0]).toBeLessThan(appendMock.mock.invocationCallOrder[0]); expect(appendMock.mock.invocationCallOrder[0]).toBeLessThan(finalizeMock.mock.invocationCallOrder[0]) })
  it('100개 단위 chunk를 순차 등록한다', async () => { const items = Array.from({ length: 205 }, (_, index) => validation(index)); const raws = Array.from({ length: 205 }, (_, index) => raw(index)); await prepareImportJob(client, { format: 'daily-brief-note-content-import', schemaVersion: 1, sourceName: null, validationResult: result(205), items, rawItems: raws, categories, approvedWarnings: new Set() }); expect(appendMock.mock.calls.map((call) => call[2].length)).toEqual([100, 100, 5]); expect(appendMock.mock.invocationCallOrder).toEqual([...appendMock.mock.invocationCallOrder].sort((a, b) => a - b)) })
  it('중간 chunk 실패 시 finalize하지 않는다', async () => { appendMock.mockRejectedValueOnce(new Error('network')); await expect(prepareImportJob(client, { format: 'daily-brief-note-content-import', schemaVersion: 1, sourceName: null, validationResult: result(1), items: [validation(0)], rawItems: [raw(0)], categories, approvedWarnings: new Set() })).rejects.toThrow('network'); expect(finalizeMock).not.toHaveBeenCalled() })
  it('기존 ready job이면 append와 finalize 없이 상세로 연결한다', async () => { createMock.mockResolvedValueOnce({ jobId: '00000000-0000-0000-0000-000000000001', isExisting: true, status: 'ready' }); const prepared = await prepareImportJob(client, { format: 'daily-brief-note-content-import', schemaVersion: 1, sourceName: 'renamed.json', validationResult: result(1), items: [validation(0)], rawItems: [raw(0)], categories, approvedWarnings: new Set() }); expect(prepared.isExisting).toBe(true); expect(appendMock).not.toHaveBeenCalled(); expect(finalizeMock).not.toHaveBeenCalled() })
  it('파일명 변경은 source fingerprint에 영향을 주지 않는다', async () => { await prepareImportJob(client, { format: 'daily-brief-note-content-import', schemaVersion: 1, sourceName: 'one.json', validationResult: result(1), items: [validation(0)], rawItems: [raw(0)], categories, approvedWarnings: new Set() }); const first = createMock.mock.calls[0][1].sourceFingerprint; createMock.mockClear(); appendMock.mockClear(); finalizeMock.mockClear(); await prepareImportJob(client, { format: 'daily-brief-note-content-import', schemaVersion: 1, sourceName: 'renamed.json', validationResult: result(1), items: [validation(0)], rawItems: [raw(0)], categories, approvedWarnings: new Set() }); expect(createMock.mock.calls[0][1].sourceFingerprint).toBe(first) })
  it('Dry Run 집계와 승인 warning 수를 create RPC에 전달한다', async () => { const warning = validation(0, 'warning'); const validationResult = result(1); validationResult.summary = { ...validationResult.summary, ready: 0, warning: 1 }; await prepareImportJob(client, { format: 'daily-brief-note-content-import', schemaVersion: 1, sourceName: null, validationResult, items: [warning], rawItems: [raw(0)], categories, approvedWarnings: new Set(['external:item-0']) }); expect(createMock).toHaveBeenCalledWith(client, expect.objectContaining({ dryRunSummary: expect.objectContaining({ warningCount: 1, acknowledgedWarningCount: 1 }) })) })
})
